### ISSUE TITLE
Extraction rule fields applied to unrelated docs

### ISSUE THREAD

**Issue by navarone-feekery** [elastic/crawler#130]
## Bug Description

ES doc fields defined by the extraction rules feature appear on _every_ doc ingested to the index, even if that doc's URL doesn't match the `url_filters` for the rule.

E.g. I have the following rule that adds fields `author` and `date` and should only apply to blog posts:

```yaml
domains:
  - url: https://www.elastic.co
    seed_urls:
      - https://www.elastic.co/search-labs
    crawl_rules:
      - policy: allow
        type: begins
        pattern: /search-labs
      - policy: deny
        type: regex
        pattern: .*

    extraction_rulesets:
      - url_filters:
          - type: regex
            pattern: "^/search-labs/blog/.+$"
      - rules:
          - action: extract
            field_name: author
            selector: ".sticky .author-name"
            join_as: array
            source: html
          - action: extract
            field_name: date
            selector: "/html/body/div[1]/main/main/article/div[2]/div[2]/div/div[3]/p[2]/time"
            join_as: string
            source: html
```

It successfully adds the values to the appropriate docs (e.g. for the URL `https://www.elastic.co/search-labs/blog/elastic-open-crawler-release`)

```json
{
  "date": "7 June 2024",
  "author": [
    "Navarone Feekery"
  ],
  "title": "Open Crawler: Elastic's Open Crawler released for tech-preview — Search Labs",
  "url": "https://www.elastic.co/search-labs/blog/elastic-open-crawler-release"
}
```

However, it also added empty fields for the URL `https://www.elastic.co/search-labs/author/navarone-feekery`

```json
{
  "date": "",
  "author": [],
  "title": "Navarone Feekery — Search Labs",
  "url": "https://www.elastic.co/search-labs/author/navarone-feekery"
}
```

### To Reproduce
1.  Add extraction rule for specific endpoint
2. Crawl
3. See that all docs have the fields from the extraction rule, even if the URL doesn't match

## Expected behavior

Unrelated docs shouldn't have a field

**Comment by navarone-feekery** [comment]
This wasn't a bug. I had misconfigured my crawler.yml file.

As can be seen in the main issue, I had the following format for extraction rules:

```yaml
    extraction_rulesets:
      - url_filters:
          - type: regex
            pattern: "/search-labs/blog/.+$"
      - rules:
          - action: extract
            field_name: author
            selector: ".sticky .author-name"
            join_as: array
            source: html
          - action: extract
            field_name: date
            selector: "/html/body/div[1]/main/main/article/div[2]/div[2]/div/div[3]/p[2]/time"
            join_as: string
            source: html
```

Notice that the `url_filters` and `rules` are not part of the same array. This meant that I was creating two extraction rulesets.

1. Ruleset 1 had the regex pattern `/search-labs/blog/.+$` but no rules
2. Ruleset 2 had all of the rules but a blank URL filter, which meant that these rules were applied to _all_ results

A corrected configuration would look like this (remove the `-` before `rules`):

```yaml
    extraction_rulesets:
      - url_filters:
          - type: regex
            pattern: "/search-labs/blog/.+$"
        rules:
          - action: extract
            field_name: author
            selector: ".sticky .author-name"
            join_as: array
            source: html
          - action: extract
            field_name: date
            selector: "/html/body/div[1]/main/main/article/div[2]/div[2]/div/div[3]/p[2]/time"
            join_as: string
            source: html
```
