### ISSUE TITLE
Elasticsearch config file takes precedence over crawler config

### ISSUE THREAD

**Issue by navarone-feekery** [elastic/crawler#159]
## Bug Description

When providing two config files to run a crawl, the ES config file is taking priority over the crawler config file. It should be the other way around.

### To Reproduce

1. Create the following ES configs using two config files:

    ```
    # crawler config file
    
    elasticsearch:
      pipeline: my-custom-pipeline
    ```
    
    ```
    # elasticsearch config file
    
    elasticsearch:
      username: <user>
      password: <password>
      host: <host>
      port: <port>
    ```
    
2. Run a crawl
3. Observe that the pipeline `my-custom-pipeline` is not used; instead `ent-search-generic-ingestion` is used

## Expected behavior

The config in the crawler file should take priority.
