### ISSUE TITLE
Failed to fetch the response after downloading 10485760 bytes (hit the response size limit of 10485760)

### ISSUE THREAD

**Issue by ZHLONG-CN** [elastic/crawler#177]
## Bug Description
Set `max_body_size` (I have set `max_body_size: 104857600`)
Run the crawler in docker, run `docker exec -it crawler bin/crawler crawl config/my-crawler.yml` will show the line 
```
[http] [crawl:676931fd1bf28a237f4c145a] [primary] Failed to fetch the response from #<Addressable::URI:0x103c URI:*****/sitemap_en.xml> after downloading 10485760 bytes (hit the response size limit of 10485760)
```

### To Reproduce
Crawl any big file.

## Expected behavior
Set a config for max response size, and fetch successfully, because my sitemap file size is less than 20MB, and greater than 10MB.

## Screenshots
/

## Environment
docker compose
```
services:
  crawler:
    image: docker.elastic.co/integrations/crawler:${CRAWLER_VERSION:-0.2.0}
    container_name: crawler
    volumes:
      - ./config:/app/config
    networks:
      - elastic
    stdin_open: true   # Equivalent to -i
    tty: true          # Required for interactive mode
    environment:
      - HTTP_PROXY=http://127.0.0.1:10809
      - HTTPS_PROXY=http://127.0.0.1:10809
      - http_proxy_host=localhost
      - http_proxy_port=8888
      - http_proxy_protocol=http
      - crawler.http.response_size.limit=104857600
      - connector.crawler.http.response_size.limit=104857600


networks:
  elastic:
    driver: bridge
```

## Additional context
/
