### ISSUE TITLE
Downloading files to a directory

### ISSUE THREAD

**Issue by asevillano** [elastic/crawler#188]
## Bug Description
With this configuration my-config.yml file inside the /app/config directory:
```
domains:
  - url: "https://www.whatsappsim.de"
    seed_urls:
      - "https://www.whatsappsim.de"
    sitemap_urls:
      - "https://www.whatsappsim.de/sitemap.xml"
    crawl_rules:
      - policy: allow
        type: regex
        pattern: ".*"
      - policy: deny
        type: ends # the type of rule, any of: begins | ends | contains | regex
        pattern: /datenschutz/
    extraction_rulesets:
      - url_filters:
          - type: regex
            pattern: ".*"
output_sink: file
output_dir: /app/downloaded_files
max_crawl_depth: 2
```
Running the crawler with this command: **docker exec -it crawler bin/crawler crawl config/my-crawler.yml**
I get his error message and the crawler doen't download any file:

```
[crawl:679a70129833d3a07d3f4334] [primary] Initialized an in-memory URL queue for up to 10000 URLs
[crawl:679a70129833d3a07d3f4334] [primary] Starting the primary crawl with up to 10 parallel thread(s)...
[crawl:679a70129833d3a07d3f4334] [primary] Crawl status: queue_size=1, pages_visited=1, urls_allowed=2, urls_denied={:already_seen=>1}, crawl_duration_msec=982, crawling_time_msec=642.0, avg_response_time_msec=642.0, active_threads=1, http_client={:max_connections=>100, :used_connections=>1}, status_codes={"200"=>1}
[crawl:679a70129833d3a07d3f4334] [primary] **Unexpected exception while sending crawl results to the output sink: undefined method `write' for Crawler::OutputSink::File:Class**
[crawl:679a70129833d3a07d3f4334] [primary] **Unexpected exception while sending crawl results to the output sink: undefined method `write' for Crawler::OutputSink::File:Class**
[crawl:679a70129833d3a07d3f4334] [primary] **Unexpected exception while sending crawl results to the output sink: undefined method `write' for Crawler::OutputSink::File:Class**
[crawl:679a70129833d3a07d3f4334] [primary] **Unexpected exception while sending crawl results to the output sink: undefined method `write' for Crawler::OutputSink::File:Class**
```
...

### To Reproduce
1. Go to directory where the repo is cloned: "../crawler"
2. Ejecute: `docker cp config/my-crawler.yml crawler:app/config/my-crawler.yml`
3. Create download directory with `docker exec --user root --workdir /app crawler mkdir downloaded_files` (otherwise is shows this error: "`Permission denied - /app/downloaded_files.  mkdir at org/jruby/RubyDir.java:677`"
4. Execute `docker exec -it crawler bin/crawler crawl config/my-crawler.yml` (I also tested `docker exec --user root -it crawler bin/crawler crawl config/my-crawler.yml` but it doesn't work)
5. See error "`Unexpected exception while sending crawl results to the output sink: undefined method `write' for Crawler::OutputSink::File:Class`"

## Expected behavior
The crawler is able to download the files to the specified directory

## Screenshots

![Image](https://github.com/user-attachments/assets/cf92947a-ef04-4cae-a57e-32718d7b2c0c)

## Environment
n/a

- OS: Windows 11
- Browser: n/a
- Version: 0.2.0
