### ISSUE TITLE
Crawler attempting to call ent-search-generic-ingestion pipeline which doesn't exist

### ISSUE THREAD

**Issue by jeffvestal** [elastic/crawler#201]
## Bug Description
When ingest pipelines are enabled and one is not specified, Open Crawler attempts to call `ent-search-generic-ingestion` pipeline. This pipeline does not exist in Serverless.

```
"status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"pipeline with id [ent-search-generic-ingestion] does not exist"}}}, {"index"=>{"_index"=>"elastic-labs", "_id"=>"e3bc5899689d6f9d9b70c950945095dd221bb130"
```

### To Reproduce
1. Create a crawler config with out specifying  `pipeline_enabled` or `elasticsearch.pipeline`
2. run crawler
3. receive error

### Workaround
Specify `pipeline_enabled: false`

## Expected behavior
ingesting docs should not fail by trying to call non-existent pipeline

## Environment
Serverless production

## Additional context
example yaml
```
 domains:
   - url: https://www.elastic.co
     seed_urls:
       - https://www.elastic.co/search-labs
       - https://www.elastic.co/observability-labs
       - https://www.elastic.co/security-labs
     crawl_rules:
       - policy: allow
         type: begins
         pattern: /search-labs
       - policy: allow
         type: begins
         pattern: /observability-labs
       - policy: allow
         type: begins
         pattern: /security-labs
       - policy: deny
         type: regex
         pattern: .*/author/.*
       - policy: deny
         type: regex
         pattern: .*

 output_sink: elasticsearch
 output_index: elastic-labs
 max_crawl_depth: 25


 elasticsearch:
   host: "https://....es.us-east-1.aws.elastic.cloud"
   port: "443"
   api_key: "..."
   bulk_api.max_items: 10
```
