### ISSUE TITLE
0.3.0 Connection Refused port 443 when launching a crawl

### ISSUE THREAD

**Issue by Skagnatti** [elastic/crawler#291]
## Bug Description
While using v0.3.0 of the crawler I am getting a connection issue with the Elasticsearch instance, with security enabled, that wasn't present while using v0.2.2.

### To Reproduce
1. Launch a crawl `# docker exec -it crawler bin/crawler crawl config/crawler.yml`
2. Output reveals a refused connection to port 443 on the Elasticsearch host
```
[2025-05-02T14:19:33.042Z] [crawl:6814d475e16dda519126b7d0] [primary] Initialized an in-memory URL queue for up to 10000 URLs
[2025-05-02T14:19:33.086Z] [crawl:6814d475e16dda519126b7d0] [primary] ES connections will be authorized with configured API key
The client is unable to verify that the server is Elasticsearch. Some functionality may not be compatible if the server is running an unsupported product.
Errno::ECONNREFUSED: Connection refused - connect(2) for "elastic" port 443
```

## Expected behavior
Result should be similar to the result when launching a crawl with v0.2.2 of the crawler
```
# docker exec -it crawler bin/crawler crawl config/crawler.yml
[crawl:6814d06ce16ddaec2ad18f81] [primary] Initialized an in-memory URL queue for up to 10000 URLs
[crawl:6814d06ce16ddaec2ad18f81] [primary] ES connections will be authorized with configured API key
[crawl:6814d06ce16ddaec2ad18f81] [primary] ES connections will use SSL with ca_fingerprint
[crawl:6814d06ce16ddaec2ad18f81] [primary] Connected to ES at https://elastic:9200 - version: 8.17.2; build flavor: default
[crawl:6814d06ce16ddaec2ad18f81] [primary] Index [search-testindex] was found!
[crawl:6814d06ce16ddaec2ad18f81] [primary] Elasticsearch sink initialized for index [search-testindex] with pipeline [search-testindex@custom]
[crawl:6814d06ce16ddaec2ad18f81] [primary] Starting the primary crawl with up to 1 parallel thread(s)...

```

## Environment

`docker-compose.yaml`
```
services:
  crawler:
    #image: docker.elastic.co/integrations/crawler:0.3.0-SNAPSHOT              # v0.3.0
    image: docker.elastic.co/integrations/crawler:${CRAWLER_VERSION:-latest} # v0.2.2
    container_name: crawler
    volumes:
     # - /opt/crawler/config:/home/app/config                                  # v0.3.0
      - /opt/crawler/config:/app/config                                       # v0.2.2
      - /var/log/crawler:/home/app/logs                                     # v0.3.0
    #  - /usr/share/enterprise-search:/app/certs
    network_mode: host
      #- elastic
    stdin_open: true   # Equivalent to -i
    tty: true          # Required for interactive mode

```

`config/crawler.yml`
```
elasticsearch:
  host: https://elastic            # v0.2.2
  #host: https://elastic:9200      # v0.3.0 attempt to force seeing the 9200
  port: 9200                       # v0.2.2
  api_key: [redacted]
  ca_fingerprint: "[fingerprint]"
  #ssl_ca_certificates: /app/certs/http_ca.crt
  pipeline: "search-testindex@custom"

...
```

## Additional context
I tried a few validations in the container itself, the ping showing it is resolving the name to IP correctly.  

```
# docker exec -it crawler ping -c 1 elastic
PING elastic (192.168..): 56 data bytes
```

And a query from outside the container from the host VM using CURL
```
# curl -v --cacert /etc/elasticsearch/certs/http_ca.crt -H "Authorization: ApiKey [redacted]" https://elastic:9200
* Rebuilt URL to: https://elastic:9200/
*   Trying 192.168.....
* TCP_NODELAY set
* Connected to elastic (192.168..) port 9200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/elasticsearch/certs/http_ca.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=elastic
*  start date: Apr  2 13:38:01 2025 GMT
*  expire date: Apr  2 13:38:01 2027 GMT
*  subjectAltName: host "elastic" matched cert's "elastic"
*  issuer: CN=Elasticsearch security auto-configuration HTTP CA
*  SSL certificate verify ok.
* TLSv1.3 (OUT), TLS app data, [no content] (0):
> GET / HTTP/1.1
> Host: elastic:9200
> User-Agent: curl/7.61.1
> Accept: */*
> Authorization: ApiKey [redacted]
>
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS app data, [no content] (0):
< HTTP/1.1 200 OK
< X-elastic-product: Elasticsearch
< content-type: application/json
< content-length: 532
<
{
  "name" : "elastic",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "DGgNsHewRNKLKN8g5sFIZQ",
  "version" : {
    "number" : "8.17.2",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "747663ddda3421467150de0e4301e8d4bc636b0c",
    "build_date" : "2025-02-05T22:10:57.067596412Z",
    "build_snapshot" : false,
    "lucene_version" : "9.12.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by mattnowzari** [comment]
Hey @Skagnatti , we have an update for you! My teammate @jedrazb was able to pinpoint the issue and wrote a fix [here](https://github.com/elastic/crawler/pull/294)

There is a _fresh_ `0.3.0-SNAPSHOT` out as of [today](https://www.docker.elastic.co/r/integrations?show_snapshots=true&ordering=-created_at), so feel free to pull it and let us know how it goes!

**Comment by Skagnatti** [comment]
Appreciate the quick turnaround. 

I ran the newer 0.3.0 but it seems to be returning the same 

```
[2025-05-05T20:37:58.865Z] [crawl:681921a6e16dda62aa96e29a] [primary] ES connections will be authorized with configured API key
The client is unable to verify that the server is Elasticsearch. Some functionality may not be compatible if the server is running an unsupported product.
Errno::ECONNREFUSED: Connection refused - connect(2) for "elastic" port 443
```

Let me know of any details I can provide that may be of assistance. My configs in the docker-compose.yaml and the config/crawler.yml are the same as they were mentioned above. I am just commenting/uncommenting the 0.2.2/0.3.0 bits as needed.

**Comment by seanstory** [comment]
You can also do a `docker image ls | grep crawler` to double check that your `0.3.0-SNAPSHOT` is from May 5, and not before

**Comment by Skagnatti** [comment]
Really appreciate the extra eyes. 

I have the following when running the 0.3.0 snapshot:
```
# docker image ls
REPOSITORY                               TAG              IMAGE ID       CREATED        SIZE
docker.elastic.co/integrations/crawler   0.3.0-SNAPSHOT   b6950379a9c3   23 hours ago   806MB
```

And when launching the crawl, of course the output mentioned prior:
```
# docker exec -it crawler bin/crawler crawl config/crawler.yml
[2025-05-06T17:19:31.961Z] [crawl:681a44a3e16dda06bbb08e26] [primary] Initialized an in-memory URL queue for up to 10000 URLs
[2025-05-06T17:19:32.066Z] [crawl:681a44a3e16dda06bbb08e26] [primary] Elasticsearch client retry configuration: 3 retries with 2s delay
[2025-05-06T17:19:32.067Z] [crawl:681a44a3e16dda06bbb08e26] [primary] ES connections will be authorized with configured API key
[2025-05-06T17:19:32.069Z] [crawl:681a44a3e16dda06bbb08e26] [primary] ES connection compression is enabled
The client is unable to verify that the server is Elasticsearch. Some functionality may not be compatible if the server is running an unsupported product.
[2025-05-06T17:19:32.340Z] [crawl:681a44a3e16dda06bbb08e26] [primary] Failed to reach ES at https://elastic:9200
```

Tried to reveal what keys are being "seen":
```
log_level => String
elasticsearch => ["host", "port", "api_key", "ca_fingerprint"]
output_sink => String
output_index => String
threads_per_crawl => Integer
max_response_size => Integer
request_timeout => Integer
binary_content_extraction_enabled => TrueClass
binary_content_extraction_mime_types => Array
domains => Array
```

When I go back to v0.2.2 the crawl starts without errors. Before I do, I am removing the 0.3.0 image like so and starting fresh:
```
# docker image ls
REPOSITORY                               TAG       IMAGE ID       CREATED        SIZE
docker.elastic.co/integrations/crawler   0.3.0-SNAPSHOT    b6950379a9c3 22 hours ago   806MB
```
`docker rmi b6950379a9c3`

Then do the uncomments/comments on the docker-compose.yaml as needed:
```
services:
  crawler:
    #image: docker.elastic.co/integrations/crawler:0.3.0-SNAPSHOT
    image: docker.elastic.co/integrations/crawler:latest          # v0.2.2
    container_name: crawler
    pull_policy: always
    volumes:
      - /opt/crawler/config:/app/config             # v0.2.2
      #- /opt/crawler/config:/home/app/config      # v0.3.0
      #- /var/log/crawler:/home/app/logs           # v0.3.0
      - /etc/elasticsearch/certs/:/app/certs        # v0.2.2
      #- /etc/elasticsearch/certs/:/home/app/certs # v0.3.0
    network_mode: host
      #- elastic
    stdin_open: true   # Equivalent to -i
    tty: true          # Required for interactive mode
```

Then start the container as v0.2.2
`docker compose up -d`

```
# docker image ls
REPOSITORY                               TAG       IMAGE ID       CREATED        SIZE
docker.elastic.co/integrations/crawler   latest    da938a31f6eb   2 months ago   1.01GB
```

And start the crawl - no changes to the config/crawler.yml file. 
```
docker exec -it crawler bin/crawler crawl config/crawler.yml
[crawl:681a4d7ae16ddad16ef00e83] [primary] Initialized an in-memory URL queue for up to 10000 URLs
[crawl:681a4d7ae16ddad16ef00e83] [primary] ES connections will be authorized with configured API key
[crawl:681a4d7ae16ddad16ef00e83] [primary] ES connections will use SSL with ca_fingerprint
[crawl:681a4d7ae16ddad16ef00e83] [primary] Connected to ES at https://elastic:9200 - version: 8.17.2; build flavor: default
[crawl:681a4d7ae16ddad16ef00e83] [primary] Index [test-search-testindex] was found!
[crawl:681a4d7ae16ddad16ef00e83] [primary] Elasticsearch sink initialized for index [test-search-testindex] with pipeline [ent-search-generic-ingestion]
[crawl:681a4d7ae16ddad16ef00e83] [primary] Starting a crawl with the following configuration:
...
[crawl:681a4d7ae16ddad16ef00e83] [primary] Crawl shutdown complete
[crawl:681a4d7ae16ddad16ef00e83] [primary] Finished a crawl. Result: success; Successfully finished the primary crawl with an empty crawl queue | Skipped purge crawl as no outdated documents were found.
[crawl:681a4d7ae16ddad16ef00e83] [primary] Releasing resources used by the crawl...
```

**Comment by seanstory** [comment]
Ah no, your error changed!
```
The client is unable to verify that the server is Elasticsearch. Some functionality may not be compatible if the server is running an unsupported product.
[2025-05-06T17:19:32.340Z] [crawl:681a44a3e16dda06bbb08e26] [primary] Failed to reach ES at https://elastic:9200
```
vs before it was:
```
The client is unable to verify that the server is Elasticsearch. Some functionality may not be compatible if the server is running an unsupported product.
Errno::ECONNREFUSED: Connection refused - connect(2) for "elastic" port 443
```

So the fix did what it was supposed to, and it's now picking up the right port. Unfortunately, that seems to not be the only issue you're facing. 👀

**Comment by seanstory** [comment]
> And a query from outside the container from the host VM using CURL

Can you repeat that process, and try doing a curl from _inside_ the crawler container? I'm wondering if your docker-compose.yml isn't setting up the network right to allow connections between your services.

**Comment by seanstory** [comment]
ChatGPT is telling me that there's a good chance that your issue is trying to do `https://elastic:9200` but also using `network: host`. You may need to be using `https://localhost:9200` instead

**Comment by Skagnatti** [comment]
Thanks for noticing the error difference. If needed, I can post this for further assistance to the discuss.elastic.co forum. 

The container doesn't have CURL installed for me to use from inside. But I can run a basic netcat against the hostname and port and it is able to see it:
```
docker exec -it crawler nc -zv elastic 9200
elastic (192.168.50.237:9200) open
```

Trying to use `https://localhost:9200` still returns with not being able to reach the Elasticsearch instance. I did change back to the "default" network configuration within the docker-compose.yaml of 

```
    networks:
        - elastic
...
networks:
  elastic:
    driver: bridge
```

Presumably that will prevent bypassing the container isolation since the Elasticsearch instance is hosted on the VM outside of the container.

If I go back to the `network_mode: host` config for the network, then I can do a query against the localhost:9200 and it will respond

```
# docker exec -it crawler nc -zv localhost 9200
localhost ([::1]:9200) open
```

**Comment by Skagnatti** [comment]
Also, if its best to mark this closed since the origianl 443 error is gone, that is OK. 

I can create a forum post about the new issue. 

Many thanks for the assistance!

**Comment by jedrazb** [comment]
Hey @Skagnatti yeah I'm struggling replicating your issue, I setup a fresh local es 8.17.2 cluster with https://www.elastic.co/docs/deploy-manage/deploy/self-managed/install-elasticsearch-docker-compose 

I started crawler same as you did:
```
services:
  crawler:
    image: docker.elastic.co/integrations/crawler:0.3.0-SNAPSHOT              
    container_name: crawler
    volumes:
      - /Users/jedr/crawler/config:/app/config
    network_mode: host
    stdin_open: true
    tty: true
```

Here is my crawler config: 

```
elasticsearch:
  host: https://localhost
  port: 9200
  username: elastic
  password: changeme
  ssl_verify: false # note for simplicity I'm skipping CA verification in this test
domains:
  - url: https://example.com

output_sink: elasticsearch
output_index: my-index
```

Started crawl with:
```
docker exec -it crawler bin/crawler crawl /app/config/test.yml
```

Crawl finished successfully.... can you first try connecting with ` ssl_verify: false ` before trying with certificates as it adds extra complexity.

**Comment by seanstory** [comment]
> I can create a forum post about the new issue.

Not necessary - all the relevant folks are already in this thread. :)

**Comment by Skagnatti** [comment]
Yes, if I add `ssl_verify: false` the crawl does indeed kick off.

**Comment by jedrazb** [comment]
Alright, this takes us one step closer. So it's an issue with verifying CA
- I see that `ssl_ca_certfificate` is commented out (but you use it for curl). FYI this config option is not supported in 0.3.0 (not sure if it was before) and should be renamed to [ca_file](https://github.com/elastic/crawler/blob/main/config/elasticsearch.yml.example#L51)
- if you intend to use `ca_fingerprint` make sure it has valid 
```
elasticsearch:
  host: https://elastic            # v0.2.2
  #host: https://elastic:9200      # v0.3.0 attempt to force seeing the 9200
  port: 9200                       # v0.2.2
  api_key: [redacted]
  ca_fingerprint: "[fingerprint]"
  #ssl_ca_certificates: /app/certs/http_ca.crt
  pipeline: "search-testindex@custom"
```
