### ISSUE TITLE
Investigate `ca_fingerprint` potentially not working in 0.3.0 (vs 0.2.2)

### ISSUE THREAD

**Issue by jedrazb** [elastic/crawler#301]
## Bug Description

We got a report that `ca_fingerprint` was working for a user in `0.2.2` but in `0.3.0` this no longer works. 

> Using the ca_fingerprint method was/is working in v0.2.2, but it doesn't seem to jive for me in v0.3.0. Commenting that out, using ca_file works fine.

https://github.com/elastic/crawler/issues/291#issuecomment-2859616695

Investigate if `ca_fingerprint` is working as expected in `0.3.0`

**Comment by navarone-feekery** [comment]
I think I was misconfiguring something. I tried a few different configurations and in the end it started working. Here's the configuration I used that worked:

```yaml
domains:
  - url: https://example.com

output_sink: elasticsearch
output_index: my-crawler-index
log_level: debug
max_crawl_depth: 1

elasticsearch:
  host: https://nav-test-9-1-0.es.us-west2.gcp.elastic-cloud.com:443
  ca_fingerprint: "<redacted>"
  ssl_verify: true
  api_key: "<redacted>"
```

I tried this with `ssl_verify: false` `ssl_verify: true` and completely removing `ssl_verify` key, and all three versions worked.
