### ISSUE TITLE
Some styles of nested YAML fields are not parsed correctly.

### ISSUE THREAD

**Issue by navarone-feekery** [elastic/crawler#327]
## Bug Description

Specifying a field twice is valid YAML syntax but isn't parsed correctly by Crawler. See:

```YAML
domains:
  - url: http://host.docker.internal:3000
    auth.type: raw
    auth.header: "Bearer <token>
```
