### ISSUE TITLE
Meta tag content attributes do not get extracted

### ISSUE THREAD

**Issue by mattnowzari** [elastic/crawler#329]
## Bug Description
When a user provides an extraction rule to extract meta tag content, the extracted fields come back as empty strings, despite the selector being correct.

### To Reproduce
1. Crawl a website with a valid CSS selector that selects a `meta` tag
Ex. 
```yaml
    extraction_rulesets:
      - url_filters:
          - type: "begins"
            pattern: "/*"
        rules:
          - action: "extract"
            field_name: article.title
            selector: 'meta[itemprop="headline"]'
            join_as: "string"
            source: "html"
```
2. Observe that the field names come up as empty strings

## Expected behavior
Open Crawler should successfully extract the `content` fields from selected `meta` tags

## Environment
n/a

## Additional context
Here is a full configuration that you can use to reproduce and test:
```yaml
domains:
  - url: https://thehackernews.com
    seed_urls:
      - https://thehackernews.com/20
    crawl_rules:
      - policy: allow
        type: regex
        pattern: \/20[2-9][0-9]\/*
      - policy: deny
        type: regex
        pattern: .*
    extraction_rulesets:
      - url_filters:
          - type: "begins"
            pattern: "/*"
        rules:
          - action: "extract"
            field_name: article.title
            selector: 'meta[itemprop="headline"]'
            join_as: "string"
            source: "html"
          - action: "extract"
            field_name: article.date
            selector: 'meta[itemprop="datePublished"]'
            join_as: "string"
            source: "html"
          - action: "extract"
            field_name: article.author
            selector: 'meta[itemprop="name"]'
            join_as: "string"
            source: "html"
          - action: "extract"
            field_name: article.tags
            selector: 'span[itemprop="articleSection"]'
            join_as: "array"
            source: "html"
          - action: "extract"
            field_name: article.body
            selector: '.articlebody'
            join_as: "string"
            source: "html"

# ---- Sink setup ----
output_sink: elasticsearch
output_index: troubleshooting_meta_tags_index

# ---- ES setup ----
elasticsearch:
  host: <host-url-here>
  port: 443
  api_key: <api-key-here>

```
